Update QCA-ALL.yml

diff --git a/.github/workflows/QCA-ALL.yml b/.github/workflows/QCA-ALL.yml
--- a/.github/workflows/QCA-ALL.yml
+++ b/.github/workflows/QCA-ALL.yml
@@ -39,9 +39,9 @@ jobs:
         run: |
           curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
           source $HOME/.cargo/env
-          rustup install stable
-          rustup default stable
-          rustup update stable
+          rustup install 1.85.0
+          rustup default 1.85.0
+          rustup update 1.85.0
 
       - name: Checkout Projects
         uses: actions/checkout@main
@@ -59,8 +59,10 @@ jobs:
 
       - name: Remove Packages
         run: |
-          sudo apt-get remove --autoremove -y $pkgs || echo "::warning::Failed to remove packages. Proceeding..."
-          sudo apt-get clean || echo "::warning::Failed to clean packages. Proceeding..."
+          echo "$gcloud_prerm" | sudo tee /var/lib/dpkg/info/google-cloud-cli-anthoscli.prerm > /dev/null
+          echo "$gcloud_prerm" | sudo tee /var/lib/dpkg/info/google-cloud-cli.prerm > /dev/null
+          sudo apt-get remove --autoremove -y $pkgs || echo "::warning::The command [sudo apt-get remove -y] failed to complete successfully. Proceeding..."
+          sudo apt-get clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
 
       - name: Call WRT-CORE Workflow
         uses: ./.github/workflows/WRT-CORE.yml
