Update QCA-ALL.yml

diff --git a/.github/workflows/QCA-ALL.yml b/.github/workflows/QCA-ALL.yml
--- a/.github/workflows/QCA-ALL.yml
+++ b/.github/workflows/QCA-ALL.yml
@@ -63,22 +63,22 @@ jobs:
           tool-cache: true
 
       - name: Initialization Environment
-         env:
-    DEBIAN_FRONTEND: noninteractive
-  run: |
-    sudo -E apt -yqq update
-    sudo -E apt -yqq full-upgrade
-    sudo -E apt -yqq autoremove --purge || echo "::warning::The command [sudo apt-get autoremove --purge] failed to complete successfully. Proceeding..."
-    sudo -E apt -yqq autoclean || echo "::warning::The command [sudo apt-get autoclean] failed to complete successfully. Proceeding..."
-    sudo -E apt -yqq clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
-    sudo -E apt -yqq install dos2unix libfuse-dev
-    sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
-    sudo -E systemctl daemon-reload
-    sudo -E timedatectl set-timezone "Asia/Shanghai"
-    sudo apt-get install -y rustup
-    rustup install 1.85.0
-    rustup default 1.85.0
-    rustup update stable
+        env:
+          DEBIAN_FRONTEND: noninteractive
+        run: |
+          sudo -E apt -yqq update
+          sudo -E apt -yqq full-upgrade
+          sudo -E apt -yqq autoremove --purge || echo "::warning::The command [sudo apt-get autoremove --purge] failed to complete successfully. Proceeding..."
+          sudo -E apt -yqq autoclean || echo "::warning::The command [sudo apt-get autoclean] failed to complete successfully. Proceeding..."
+          sudo -E apt -yqq clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
+          sudo -E apt -yqq install dos2unix libfuse-dev
+          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
+          sudo -E systemctl daemon-reload
+          sudo -E timedatectl set-timezone "Asia/Shanghai"
+          sudo apt-get install -y rustup
+          rustup install 1.85.0
+          rustup default 1.85.0
+          rustup update stable
 
       - name: Initialization Values
         run: |
