Update WRT-CORE.yml

diff --git a/.github/workflows/WRT-CORE.yml b/.github/workflows/WRT-CORE.yml
--- a/.github/workflows/WRT-CORE.yml
+++ b/.github/workflows/WRT-CORE.yml
@@ -64,8 +64,8 @@ jobs:
         run: |
           curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
           source $HOME/.cargo/env
-          rustup update stable
-          rustup default stable
+          rustup update nightly
+          rustup default nightly
 
       - name: Checkout Projects
         uses: actions/checkout@main
@@ -87,9 +87,18 @@ jobs:
         run: |
           sudo -E apt -yqq update
           sudo -E apt -yqq full-upgrade
-          sudo -E apt -yqq autoremove --purge || echo "::warning::The command [sudo apt-get autoremove --purge] failed to complete successfully. Proceeding..."
-          sudo -E apt -yqq autoclean || echo "::warning::The command [sudo apt-get autoclean] failed to complete successfully. Proceeding..."
-          sudo -E apt -yqq clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
+          for i in {1..3}; do
+            sudo -E apt -yqq autoremove --purge && break || echo "::warning::The command [sudo apt-get autoremove --purge] failed to complete successfully. Retrying... ($i)"
+            sleep 5
+          done
+          for i in {1..3}; do
+            sudo -E apt -yqq autoclean && break || echo "::warning::The command [sudo apt-get autoclean] failed to complete successfully. Retrying... ($i)"
+            sleep 5
+          done
+          for i in {1..3}; do
+            sudo -E apt -yqq clean && break || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Retrying... ($i)"
+            sleep 5
+          done
           sudo -E apt -yqq install dos2unix libfuse-dev
           sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
           sudo -E systemctl daemon-reload
